### ISSUE TITLE
HARP does not exit model loading state after attempting to load invalid model.

### ISSUE THREAD

**Issue by cwitkowitz** [TEAMuP-dev/HARP#104]
If you open up HARP, type in an invalid path, and try to load, a window with an error message will appear. After closing the window, the load button is still semi-transparent with the text "loading...", and there is the message "loading <INVALID_PATH>... if this takes a while ..." in the middle of the plugin window. It seems to be stuck here.

**Comment by xribene** [comment]
Frank, do you still have this issue? I can't replicate it. I think this was fixed in a past commit, but I must have forgotten to close the issue.

**Comment by cwitkowitz** [comment]
Yes, the state issue seems to be fixed, but the bad path is now added to the dropdown and the GUI link to attempt to open the HuggingFace Space is still added.

**Comment by cwitkowitz** [comment]
Closing for now as this is no longer reproducible. The remaining issues are now captured by #143.
