### ISSUE TITLE
undo history

### ISSUE THREAD

**Issue by hugofloresgarcia** [TEAMuP-dev/HARP#108]
at the moment, HARP is VERY destructive! it won't even let you undo an operation after you've processed with a model. 

Instead, we should apply all modifications to a temporary file and then let the user manually "commit" and save the changes to the original file.

**Comment by hugofloresgarcia** [comment]
added "commit changes" button in v1.0.0

**Comment by bryan-pardo** [comment]
replaced this issue with another one that is about the same thing
