### ISSUE TITLE
Pressing play doesn't clear existing audio from thumbnail when zoomed in.

### ISSUE THREAD

**Issue by cwitkowitz** [TEAMuP-dev/HARP#162]

**Comment by bryan-pardo** [comment]
Frank said they fixed this

**Comment by cwitkowitz** [comment]
If the audio file is small enough, this still happens even when there is no zoom.

**Comment by cwitkowitz** [comment]
I don't think this issue is relevant anymore, since we moved away from the follow-transport style of displaying media.
