### ISSUE TITLE
Harp can't load a model on Windows 11

### ISSUE THREAD

**Issue by bryan-pardo** [TEAMuP-dev/HARP#164]
HARP starts up in Windows 11 and links to reaper. What it doesn't do is load a model. When I go to load a model, it can't find the path. HEre's what the log says when I tried loading 2 models.  NOTE: I confirmed I could load both models from MacOS HARP. Same room, network, and version number (the latest one).

**********************************************************
hello, harp!
Log started: 4 Jun 2024 11:23:57am

url: hugggof/nesquik
Running command: start /B cmd /c set PYTHONIOENCODING=UTF-8 && C:\Users\bryan\Downloads\Resources\gradiojuce_client\gradiojuce_client.exe --mode get_ctrls --url hugggof/nesquik --output_path C:\Users\bryan\AppData\Local\Temp\control_spec.json >> C:\Users\bryan\AppData\Local\Temp\system_get_ctrls_log.txt 2>&1
The system cannot find the path specified.

**********************************************************
hello, harp!
Log started: 4 Jun 2024 11:24:32am

url: hugggof/pitch_shifter
Running command: start /B cmd /c set PYTHONIOENCODING=UTF-8 && C:\Users\bryan\Downloads\Resources\gradiojuce_client\gradiojuce_client.exe --mode get_ctrls --url hugggof/pitch_shifter --output_path C:\Users\bryan\AppData\Local\Temp\control_spec.json >> C:\Users\bryan\AppData\Local\Temp\system_get_ctrls_log.txt 2>&1
The system cannot find the path specified.

**********************************************************
hello, harp!
Log started: 4 Jun 2024 11:25:28am

**Comment by xribene** [comment]
I can't reproduce this. It works for me in both win10 and win11 64bit. 

Based on the log, I think the gradiojuce_client.exe cannot be found.
The steps I'd follow to debug this would be:
1. I'd extract the  HARP-1.2.0-Windows.zip into its own folder and not in Downloads, in case there are previous versions of HARP floating there in the Downloads.
2. Using the explorer, I'd manually check if the  file exist
 - `C:\Users\bryan\Downloads\Resources\gradiojuce_client\gradiojuce_client.exe`
 - if the zip extraction is done the way I describe above, the file should be in 
 `C:\Users\bryan\Downloads\HARP-1.2.0-Windows\Resources\gradiojuce_client\gradiojuce_client.exe`

**Comment by bryan-pardo** [comment]
That's the issue! I didn't have the whole .zip file extracted, so the helper dlls, etc were not there. Once I unzip the whole folder of stuff it works.

I note that the gradio client is an .exe. That probably explains why a command line briefly appears when I click on a button that causes a call to gradio.
