### ISSUE TITLE
Desperately needs at least 1 level of undo

### ISSUE THREAD

**Issue by bryan-pardo** [TEAMuP-dev/HARP#167]
To edit something in your DAW workflow you (1) start Harp (2) hit "load model" (3) wait 10 seconds (4) listen to the output....and then if you don't like what you did, you can't just turn a dial a bit and try again, because the audio is already altered. Instead, you have to quit Harp and restart the whole process. This is pretty awkward.   If we had even 1 level of 'undo', it would help a ton.

**Comment by cwitkowitz** [comment]
It would also be nice to add a "restore" option to revert back to the original file.

**Comment by bryan-pardo** [comment]
I just checked Logic Pro, Audacity and Audition. None of them have this "restore" option.  Could the user just re-load the file to get "restore" to happen?

**Comment by cwitkowitz** [comment]
Yes they can just reload (unless they overwrite the original). Just figured it could be a nice feature to have.

**Comment by bryan-pardo** [comment]
We now have undo!
