### ISSUE TITLE
Saving the HARP output doesn't give a default file extension (Linux) 

### ISSUE THREAD

**Issue by bryan-pardo** [TEAMuP-dev/HARP#184]

**Comment by bryan-pardo** [comment]
In MacOS, if you leave off a file extension, it adds .wav. If you pick another supported extension (like .ogg) it saves just fine.  If you pick a non-supported extension (like .xml) HARP tells you it cannot save in that format and tells you ".wav" is required (even though multiple formats are supported).

More interesting...if you save audio as ".mid" it lets you. That's a bug for sure.

**Comment by NathanPruyne** [comment]
On Windows and Linux the non-supported extensions are not throwing errors either (the outputted file is a .wav but with whatever extension that's been put).
