### ISSUE TITLE
Create a website for HARP.

### ISSUE THREAD

**Issue by cwitkowitz** [TEAMuP-dev/HARP#83]
As noted in https://github.com/audacitorch/HARP/issues/74#issuecomment-1841018267, it would be good to have an official website for HARP, where we could more elegantly lay out things such as currently available HARP-compatible models.

**Comment by xribene** [comment]
Ok here is a website draft: [harp-plugin.netlify.app](https://harp-plugin.netlify.app/)

It's made using vitepress. We mostly need to write markdown files which vitepress parses them to html.
Color customization is very easy using css variables. We can also create some custom components like the team view you'll see if you click "Get Started". 
Also, if you click "API" at the navbar on the top right, you can see the doxygen documentation of our source code. 

What is still not clear to me is whether the website source code should be in a separate repo or be a subfolder inside the HARP repo. For example the doxygen doc files are already in the HARP repo. Both approaches have advantages. 
### Website/Docs and Code in the same repo
#### Pros

- Documentation is versioned along with the code.
- Common commits/PRs history timeline for both code and website/documentation
- 
#### Cons
- Increased repo size. 

Any thoughts ?

**Comment by hugofloresgarcia** [comment]
I would be pro-keeping them in the same repo so we can keep version control clean?

**Comment by bryan-pardo** [comment]
We have a website
